void reportparams(FILE* fd, char* fn, Course* c);
void reportfreqs(FILE* fd, Stats* s);
void histo(FILE* fd, int bins[], float min, float max, int cnt);
void reportmoments(FILE* fd, Stats* s);
void reportcomposites(FILE* fd, Course* c, int nm);
void reportquantiles(FILE* fd, Stats* s);
void reportquantilesummaries(FILE* fd, Stats* s);
void reporthistos(FILE* fd, Course* c, Stats* s);
void reportscores(FILE* fd, Course* c, int nm);
void reporttabs(FILE* fd, Course* c);
